name: 'wwwqr sec check'
description: 'Looks for unsave functions in code'
inputs:
  test-check:
    description: 'Runs the test case'
    required: true
    default: 'All good'
  whitelist:
    description: Whitelist the paths to suspisious files
    required: true
    default: whitelist.ini
  checker:
    description: repo release version
    required: false
outputs:
  random-int:
    description: "Random int"
    value: ${{ steps.rand-num-gen.outputs.rand-num }}
  test-file-data:
    description: "File content from test.txt"
    value: ${{ steps.file-data-gen.outputs.file-data }}
  download-stat:
    description: "Status of downloading assets with action"
    value: $({ steps.download.outputs.download-stat })
runs:
  using: "composite"
  steps:
    - name: Run test case
      run: echo "Test status is $TEST_VALUE."
      shell: bash
      env:
        TEST_VALUE: ${{ inputs.test-check }}

    - name: Random num generator
      id: rand-num-gen
      run: echo "rand-num=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    
    - name: Download assets
      id: download
      run: echo "download-stat=$(git clone -b $RELEASE_VERSION https://github.com/Virtual-Vitality-Project/composite-wwwqr-sec-check.git)" >> $GITHUB_OUTPUT
      shell: bash
      env:
        RELEASE_VERSION: ${{ inputs.checker }}

    - name: Run checker
      id: checker-runner
      run: |
        cd composite-wwwqr-sec-check/checker
        mv * ../
        cd ../
        rm -R checker
        g++ main.cpp
        mv a.out check
        chmod 0777 check
        echo "checker-run-result=$(./check)" >> $GITHUB_OUTPUT
      shell: bash

    - name: text.txt check
      run: ls -l test.txt & cat test.txt
      shell: bash

    - name: File data test
      id: file-data-gen
      run: echo "file-data=$(cat test.txt)" >> $GITHUB_OUTPUT
      shell: bash
