name: 'wwwqr sec check'
description: 'Looks for unsave functions in code'
inputs:
  whitelist:
    description: Whitelist the paths to suspisious files
    required: true
  checker:
    description: repo release version
    required: true
outputs:
  checker-full-result:
    description: Checks all the code with all filters
    value: ${{ steps.checker-runner.outputs.checker-run-result }}
runs:
  using: "composite"
  steps:
    - name: Download assets
      id: download
      run: echo "download-stat=$(git clone -b $RELEASE_VERSION https://github.com/Virtual-Vitality-Project/composite-wwwqr-sec-check.git)" >> $GITHUB_OUTPUT
      shell: bash
      env:
        RELEASE_VERSION: ${{ inputs.checker }}

    - name: Run checker
      id: checker-runner
      run: |
        cd composite-wwwqr-sec-check/checker
        mv * ../
        cd ../
        rm -R checker
        ls -a
        g++ main.cpp
        mv a.out check
        chmod 0777 check
        ./check $WHITELIST_FILE
      shell: bash
      env:
        WHITELIST_FILE: ${{ inputs.whitelist }}
