name: security-checker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:  
  wwwqr_sec_check_job:
    runs-on: ubuntu-latest
    name: Looking for your bad code
    steps:
      - uses: actions/checkout@v4
      - id: wwwqr
        uses: actions/composite-wwwqr-sec-check@v1
        with:
          test-check: 'Alles is goed?'
      - run: echo the rand num is "$RAND_NR"
        shell: bash
        env:
          RAND_NR: ${{ steps.wwwqr.outputs.rand-num-gen }}
